log:
  consoleLevel: debug
  fileLevel: error
  logFilePath: ""
transfer:
  maxBidiRemoteStreams: 100
  maxIdleTimeout: -1
  keepAlivePeriod: 10
inbounds:
  - tag: p1
    address: 127.0.0.1
    port: 1080
    protocol: socks
  - tag: p2
    address: 127.0.0.1
    port: 1081
    protocol: http
outbounds:
  - tag: s1
    address: 127.0.0.1
    port: 23456
    nodePort: 21086
routing:
  rules:
    - inTag: p1
      outTag: s1
      ip:
        - "!USA"
        - "!PRIVATE"
    - inTag: p2
      outTag: s1
      ip:
        - "!USA"
        - "!PRIVATE"